Description: |
  Downloads the latest version of Docker for Windows
Identifier: com.github.jpiperberg.download.Docker-Win-x86
Input:
  NAME: Docker
  ARCH: amd64 # pass arm64 for arm
MinimumVersion: 2.3.0
Process:
- Processor: URLDownloader
  Arguments:
    url: 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-win-%ARCH%'
    filename: '%NAME%-%ARCH%.exe'
- Processor: com.github.jpiperberg.SharedProcessors/OsslsigncodeVerifier.py
  Arguments:
    signer_string: 'CN=Docker Inc,O=Docker Inc,L=Palo Alto,ST=California,C=US,serialNumber=4817464,businessCategory=Private Organization,jurisdictionST=Delaware,jurisdictionC=US
- Processor: 'com.github.hansen-m.SharedProcessors/WinInstallerExtractor'
  Arguments:
    exe_path: '%pathname%'
    extract_dir: 'ExeExtract'
- Processor: PathDeleter
  Arguments:
    path_list:
      - '%RECIPE_CACHE_DIR%/ExeExtract'
